### GET /api/registrations
GET http://localhost:5069/api/registrations

### POST /api/registrations
POST http://localhost:5069/api/registrations
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com"
}

### GET /api/registrations/{id}
GET http://localhost:5069/api/registrations/1
